'use strict';
// 示例单独上台验收；Playwright 住临时目录也能演，PLAYWRIGHT_MODULE 负责报住址。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const checks = [];
  const check = (name, actual, expected = true) => {
    assert.deepEqual(actual, expected, name);
    checks.push(name);
  };
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1.5 });
    const errors = [], external = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (!request.url().startsWith('file:')) external.push(request.url()); });
    await page.goto(pathToFileURL(path.resolve(__dirname, '../../design/cloud-mint-example.html')).href);
    check('没有无关导航或说明卡', await page.locator('nav, .route, .security').count(), 0);
    check('设置表单存在', await page.locator('#settingsForm').count(), 1);
    check('密钥只提供环境变量名', await page.locator('#keyEnv').inputValue(), 'CPA_RELAY_KEY');
    check('不提供密码或令牌输入框', await page.locator('input[type=password]').count(), 0);
    check('有四条示例票记录', await page.locator('#rows tr').count(), 4);
    await page.selectOption('#status', 'ready');
    check('状态筛选', await page.locator('#rows tr').count(), 2);
    await page.selectOption('#transport', 'WS');
    check('协议筛选', await page.locator('#rows tr').count(), 1);
    await page.fill('#search', '不存在');
    check('空结果提示', (await page.locator('#rows').textContent()).includes('没有符合条件'));
    await page.click('#reset');
    check('重置筛选', await page.locator('#rows tr').count(), 4);
    check('前置代理默认留空直连', await page.locator('#proxyURL').inputValue(), '');
    await page.fill('#proxyURL', 'socks5h://127.0.0.1:1080');
    await page.click('#saveSettings');
    check('可保存前置代理示例', await page.locator('#settingsMessage').getAttribute('data-kind'), 'success');
    await page.fill('#proxyURL', 'ftp://127.0.0.1:21');
    await page.click('#saveSettings');
    check('拒绝不支持的前置代理协议', await page.locator('#settingsMessage').getAttribute('data-kind'), 'error');
    await page.click('#discardSettings');
    await page.locator('#advancedSettings').evaluate(el => { el.open = true; });
    await page.fill('#proxyEnv', 'CPA_MINT_PROXY');
    await page.click('#saveSettings');
    check('代理地址与环境变量互斥', await page.locator('#settingsMessage').getAttribute('data-kind'), 'error');
    await page.fill('#proxyURL', '');
    await page.click('#saveSettings');
    check('可改用代理环境变量', await page.locator('#settingsMessage').getAttribute('data-kind'), 'success');
    await page.click('#reset');
    await page.fill('#gateway', 'unified-199');
    check('标记未保存', await page.locator('#settingsState').textContent(), '未保存');
    await page.click('#saveSettings');
    check('保存仅修改示例', (await page.locator('#settingsMessage').textContent()).includes('仅当前示例生效'));
    check('保存后标记已应用', await page.locator('#settingsState').textContent(), '已应用示例');
    check('历史票不被设置改写', (await page.locator('#rows').textContent()).includes('unified-88'));
    await page.fill('#gateway', 'unified-7');
    await page.click('#discardSettings');
    check('放弃改动回到已保存值', await page.locator('#gateway').inputValue(), 'unified-199');
    await page.fill('#endpoint', 'https://user:secret@HOST/?token=secret');
    await page.click('#saveSettings');
    check('拒绝带凭据和查询参数的地址', await page.locator('#settingsMessage').getAttribute('data-kind'), 'error');
    await page.click('#discardSettings');
    await page.locator('#advancedSettings').evaluate(el => { el.open = true; });
    await page.fill('#waitMs', '10000');
    await page.fill('#timeoutMs', '100');
    await page.click('#saveSettings');
    check('后台超时不能小于业务等待', await page.locator('#settingsMessage').getAttribute('data-kind'), 'error');
    await page.click('#discardSettings');
    await page.fill('#ticketLength', '0');
    await page.click('#saveSettings');
    check('拒绝非法票长', await page.locator('#settingsMessage').getAttribute('data-kind'), 'error');
    await page.click('#discardSettings');
    await page.uncheck('#enabled');
    await page.click('#saveSettings');
    check('示例启停设置生效', await page.locator('#enabledStatus').textContent(), '示例已停用');
    await page.selectOption('#mintTransport', 'websocket');
    await page.click('#saveSettings');
    await page.reload();
    check('不持久化设置', await page.locator('#mintTransport').inputValue(), 'sse');
    check('刷新恢复默认演示开关', await page.locator('#enabled').isChecked());
    await page.click('#follow');
    check('流水跟随开关', await page.locator('#follow').getAttribute('aria-pressed'), 'false');
    await page.click('#follow');
    check('桌面不横向溢出', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.resolve(__dirname, '../../design/cloud-mint-example-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    check('手机设置可用', await page.locator('#settingsForm').isVisible());
    check('手机不横向溢出', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.resolve(__dirname, '../../design/cloud-mint-example-mobile.png'), fullPage: true });
    check('没有脚本错误', errors, []);
    check('没有网络请求', external, []);
    console.log(`PASS ${checks.length} checks: ${checks.join(' / ')}`);
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
